var extId = window.location.hash.substr(1);
var idToType = {};
var usercode = {};

console.log("extension id: ", extId);

function receivedResponse(resp) {
    console.log(resp);
    if (resp.event === "extinit")
      console.log('initialized!')
}

window.onload = function(e){ 
    console.log("window.onload", e, Date.now()); 
    window.addEventListener("message", function(ev) {
        var resp = ev.data;
        if (resp && resp.type === "pxtpkgext")
            receivedResponse(resp);
        }, false);
        sendRequest("extinit");
}


function sendRequest(action) {
    var id = Math.random().toString();
    var msg = {
        type: "pxtpkgext",
        action: action,
        extId: extId,
        response: true,
        id: id
    };
    window.parent.postMessage(msg, "*");
}

function sendGeneratedCode(body) {
    var id = Math.random().toString();
    var msg = {
        id: id,
        type: "pxtpkgext",
        action: "extwritecode",
        extId: extId,
        body: body
    }
    window.parent.postMessage(msg, "*");
}

function renderUserCode() {
    var ts = `// This file was autogenerated, do not edit.
namespace layoutdesigner {

/*
* A neopixel layout
*/
//% blockId="testblock" block="testblock %num"   
export function testing(num: number): number {
    return num;
}
}` 
    return ts;
}

function saveUserCode() {            
    var ts = renderUserCode();
    console.log("Saving generated blocks: ", ts);
    sendGeneratedCode({code: ts, json: JSON.stringify(usercode, null, 2)});
}