var extId = window.location.hash.substr(1);
var idToType = {};
var usercode = {};
var countTest = 0;

console.log("extension id: ", extId);

function receivedResponse(resp) {
    console.log(resp);
    if (resp.event === "extinit")
      console.log('initialized!')
}

window.onload = function(e){ 
    window.addEventListener("message", function(ev) {
        var resp = ev.data;
        if (resp && resp.type === "pxtpkgext") {
            console.log("resp: ", resp);
            receivedResponse(resp);
        }
        }, false);
    sendRequest("extinit");
}

function sendRequest(action) {
    var id = Math.random().toString();
    var msg = {
        type: "pxtpkgext",
        action: action,
        extId: extId,
        response: true,
        id: id
    };
    window.parent.postMessage(msg, "*");
}

function sendGeneratedCode(body) {
    var id = Math.random().toString();
    var msg = {
        id: id,
        type: "pxtpkgext",
        action: "extwritecode",
        extId: extId,
        body: body
    }
    window.parent.postMessage(msg, "*");
}

function renderUserCode(count) {
    var ts = `// This file was autogenerated, do not edit.
namespace layoutdesigner {

/*
* A neopixel layout
*/
//% blockId="testblock` + count.toString() + `" block="testblock` + count.toString() + `%num"   
export function testing` + count.toString() + `(num: number): number {
    return num;
}
}` 
    return ts;
}

function saveUserCode() {     
    var ts = renderUserCode(countTest);
    countTest++;
    console.log("Saving generated blocks: ", ts);
    sendGeneratedCode({code: ts, json: JSON.stringify(usercode, null, 2)});
}